import { ProgrammeLevel, AcademicSemester } from '@prisma/client';

export interface SeedFaculty {
  id: string;
  facultyCode: string;
  name: string;
  deanEmail?: string;
  departments: {
    id: string;
    name: string;
    hodEmail?: string;
    programmes: {
      id: string;
      programmeCode: string;
      name: string;
      degreeTitle: string;
      programmeDescription: string;
      level: ProgrammeLevel;
    }[];
  }[];
}

export const ACADEMIC_TAXONOMY: SeedFaculty[] = [
  // 1. Faculty of Agricultural Sciences (7 Programmes)
  {
    id: 'agr',
    facultyCode: 'F01',
    name: 'Faculty of Agricultural Sciences',
    deanEmail: 'dean.agric@noun.edu.ng',
    departments: [
      {
        id: 'AEE',
        name: 'Agricultural Economics and Extension',
        hodEmail: 'hod.aee@noun.edu.ng',
        programmes: [
          {
            id: 'AGR201',
            programmeCode: 'P010101',
            name: 'B.Agric Agricultural Economics and Agro-Business',
            degreeTitle: 'B.Agric',
            programmeDescription: 'Comprehensive training in agricultural economics, farm management, marketing, and agribusiness entrepreneurship.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'AGR202',
            programmeCode: 'P010102',
            name: 'B.Agric Agricultural Extension and Rural Development',
            degreeTitle: 'B.Agric',
            programmeDescription: 'Training in participatory rural appraisal, extension methodologies, and agricultural innovation adoption.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'AGR301',
            programmeCode: 'P010103',
            name: 'PGD Agricultural Extension and Management',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma providing bridge competencies in agricultural extension and rural advisory services.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'AGR206',
            programmeCode: 'P010104',
            name: 'B.Agric Agricultural Extension and Community Development',
            degreeTitle: 'B.Agric',
            programmeDescription: 'Community-driven agricultural development, rural leadership, and extension communication.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'ASF',
        name: 'Animal Science and Fisheries',
        hodEmail: 'hod.asf@noun.edu.ng',
        programmes: [
          {
            id: 'AGR203',
            programmeCode: 'P010201',
            name: 'B.Agric Animal Science',
            degreeTitle: 'B.Agric',
            programmeDescription: 'Scientific study of livestock nutrition, genetics, breeding, and husbandry.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'CSI',
        name: 'Crop and Soil Science',
        hodEmail: 'hod.csi@noun.edu.ng',
        programmes: [
          {
            id: 'AGR204',
            programmeCode: 'P010301',
            name: 'B.Agric Crop Science',
            degreeTitle: 'B.Agric',
            programmeDescription: 'Principles of agronomy, crop physiology, crop protection, and sustainable farming systems.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'AGR205',
            programmeCode: 'P010302',
            name: 'B.Agric Soil Science',
            degreeTitle: 'B.Agric',
            programmeDescription: 'Soil chemistry, pedology, fertility management, and soil conservation.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
    ],
  },

  // 2. Faculty of Arts (31 Programmes)
  {
    id: 'art',
    facultyCode: 'F02',
    name: 'Faculty of Arts',
    deanEmail: 'dean.arts@noun.edu.ng',
    departments: [
      {
        id: 'LNG',
        name: 'Linguistics, Foreign and Nigerian Languages',
        hodEmail: 'hod.lng@noun.edu.ng',
        programmes: [
          {
            id: 'ART201',
            programmeCode: 'P020101',
            name: 'B.A. French',
            degreeTitle: 'B.A.',
            programmeDescription: 'French linguistics, Francophone literature, and professional translation.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART205',
            programmeCode: 'P020102',
            name: 'B.A. Hausa',
            degreeTitle: 'B.A.',
            programmeDescription: 'Hausa syntax, phonology, oral literature, and modern cultural studies.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART206',
            programmeCode: 'P020103',
            name: 'B.A. Igbo',
            degreeTitle: 'B.A.',
            programmeDescription: 'Igbo linguistics, morphology, creative writing, and Igbo cultural heritage.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART207',
            programmeCode: 'P020104',
            name: 'B.A. Yoruba',
            degreeTitle: 'B.A.',
            programmeDescription: 'Yoruba language, literature, poetic forms, and sociolinguistics.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART210',
            programmeCode: 'P020105',
            name: 'B.A. Arabic Language and Literature',
            degreeTitle: 'B.A.',
            programmeDescription: 'Arabic syntax, morphology, classical and modern Arabic literary texts.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART410',
            programmeCode: 'P020106',
            name: 'M.A. Arabic',
            degreeTitle: 'M.A.',
            programmeDescription: 'Advanced research in Arabic grammar, literary theory, and comparative analysis.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART411',
            programmeCode: 'P020107',
            name: 'M.A. French',
            degreeTitle: 'M.A.',
            programmeDescription: 'Advanced French linguistics, semantics, and African Francophone literature.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART412',
            programmeCode: 'P020108',
            name: 'M.A. Hausa',
            degreeTitle: 'M.A.',
            programmeDescription: 'Advanced Hausa linguistics, comparative literary traditions, and dialectology.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART610',
            programmeCode: 'P020109',
            name: 'Ph.D. Arabic',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral dissertation in Arabic linguistic thought, Islamic manuscripts, and literature.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'RST',
        name: 'Religious Studies',
        hodEmail: 'hod.rst@noun.edu.ng',
        programmes: [
          {
            id: 'ART203',
            programmeCode: 'P020201',
            name: 'B.A. Islamic Studies',
            degreeTitle: 'B.A.',
            programmeDescription: 'Islamic jurisprudence (Fiqh), Hadith sciences, Quranic exegesis, and Islamic civilization.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART208',
            programmeCode: 'P020202',
            name: 'B.A. Christian Religious Studies',
            degreeTitle: 'B.A.',
            programmeDescription: 'Biblical studies, Christian ethics, church history, and systematic theology.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'ART301',
            programmeCode: 'P020203',
            name: 'PGD Christian Religious Studies',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate bridge curriculum in Christian theology and hermeneutics.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'ART402',
            programmeCode: 'P020204',
            name: 'M.A. Christian Religious Studies (Old Testament)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Advanced Hebrew exegesis, Old Testament theology, and historical context.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART403',
            programmeCode: 'P020205',
            name: 'M.A. Christian Religious Studies (New Testament)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Greek text exegesis, Pauline theology, and early Christian origins.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART404',
            programmeCode: 'P020206',
            name: 'M.A. Christian Religious Studies (Church History)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Historiography of the Christian church, patristics, and African Christianity.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART405',
            programmeCode: 'P020207',
            name: 'M.A. Christian Religious Studies (Systematic Theology)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Systematic doctrine, Christian ethics, and philosophical theology.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART406',
            programmeCode: 'P020208',
            name: 'M.A. Christian Religious Studies (African Traditional Religion)',
            degreeTitle: 'M.A.',
            programmeDescription: 'African religious beliefs, phenomenology, and inter-religious encounters.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART407',
            programmeCode: 'P020209',
            name: 'M.A. Islamic Studies (Hadith)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Methodology of Hadith criticism (Mustalah al-Hadith) and narration chains.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART408',
            programmeCode: 'P020210',
            name: 'M.A. Islamic Studies (Islamic Jurisprudence)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Principles of Islamic jurisprudence (Usul al-Fiqh) and comparative legal schools.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART409',
            programmeCode: 'P020211',
            name: 'M.A. Islamic Studies (Islamic History)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Islamic historiography, caliphate eras, and Islam in West Africa.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART413',
            programmeCode: 'P020212',
            name: 'M.A. Christian Religious Studies (Philosophy of Religion)',
            degreeTitle: 'M.A.',
            programmeDescription: 'Epistemology of religion, religious language, and the problem of evil.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'ART602',
            programmeCode: 'P020213',
            name: 'Ph.D. Christian Religious Studies (Old Testament)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research in ancient Near Eastern biblical contexts and OT theology.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART603',
            programmeCode: 'P020214',
            name: 'Ph.D. Christian Religious Studies (New Testament)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research in Hellenistic Greek texts and New Testament hermeneutics.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART604',
            programmeCode: 'P020215',
            name: 'Ph.D. Christian Religious Studies (Church History)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral thesis in Nigerian and global church historical developments.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART605',
            programmeCode: 'P020216',
            name: 'Ph.D. Christian Religious Studies (Systematic Theology)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research in contemporary theology, christology, and pneumatology.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART606',
            programmeCode: 'P020217',
            name: 'Ph.D. Christian Religious Studies (African Traditional Religion)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Original doctoral investigation into indigenous African ontology and rituals.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART607',
            programmeCode: 'P020218',
            name: 'Ph.D. Islamic Studies (Hadith)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral contributions to Hadith authentication and thematic canonical studies.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART608',
            programmeCode: 'P020219',
            name: 'Ph.D. Islamic Studies (Islamic Jurisprudence)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into contemporary Islamic commercial and family law.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'ART609',
            programmeCode: 'P020220',
            name: 'Ph.D. Islamic Studies (Islamic History)',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral analysis of Islamic institutions and intellectual history.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'ENG',
        name: 'English',
        hodEmail: 'hod.eng@noun.edu.ng',
        programmes: [
          {
            id: 'ART204',
            programmeCode: 'P020301',
            name: 'B.A. English',
            degreeTitle: 'B.A.',
            programmeDescription: 'Comprehensive English language studies, literary criticism, stylistics, and creative writing.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'PHL',
        name: 'Philosophy',
        hodEmail: 'hod.phl@noun.edu.ng',
        programmes: [
          {
            id: 'ART209',
            programmeCode: 'P020401',
            name: 'B.A. Philosophy',
            degreeTitle: 'B.A.',
            programmeDescription: 'Logic, ethics, epistemology, African philosophy, metaphysics, and political thought.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
    ],
  },

  // 3. Faculty of Education (25 Programmes)
  {
    id: 'edu',
    facultyCode: 'F03',
    name: 'Faculty of Education',
    deanEmail: 'dean.education@noun.edu.ng',
    departments: [
      {
        id: 'SED',
        name: 'Science Education',
        hodEmail: 'hod.sed@noun.edu.ng',
        programmes: [
          {
            id: 'EDU201',
            programmeCode: 'P030101',
            name: 'B.Sc. (Ed.) Agricultural Science',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Agricultural science pedagogy, farm practice instruction, and curriculum design.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU202',
            programmeCode: 'P030102',
            name: 'B.Sc. (Ed.) Biology',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Biology teaching methods, laboratory management, and educational psychology.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU204',
            programmeCode: 'P030103',
            name: 'B.Sc. (Ed.) Chemistry',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Chemistry pedagogy, safety protocols, and laboratory demonstration skills.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU205',
            programmeCode: 'P030104',
            name: 'B.Sc. (Ed.) Computer Science',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Computer science education, programming pedagogy, and digital instructional tools.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU211',
            programmeCode: 'P030105',
            name: 'B.Sc. (Ed.) Integrated Science',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Integrated STEM pedagogy for junior and senior secondary educational tiers.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU213',
            programmeCode: 'P030106',
            name: 'B.Sc. (Ed.) Mathematics',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Mathematics instruction, logic heuristics, and quantitative problem solving.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU214',
            programmeCode: 'P030107',
            name: 'B.Sc. (Ed.) Physics',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Physics pedagogy, experimental instrumentation, and conceptual physics modeling.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU404',
            programmeCode: 'P030108',
            name: 'M.Ed. Science Education',
            degreeTitle: 'M.Ed.',
            programmeDescription: 'Advanced research in STEM educational methods, assessment, and curriculum innovation.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'EDU604',
            programmeCode: 'P030109',
            name: 'Ph.D. Science Education',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into science cognitive psychology and STEM educational policy.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'EDU605',
            programmeCode: 'P030110',
            name: 'Ph.D. Educational Technology',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral thesis in instructional design, e-learning paradigms, and educational media.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'ASE',
        name: 'Arts and Social Science Education',
        hodEmail: 'hod.ase@noun.edu.ng',
        programmes: [
          {
            id: 'EDU203',
            programmeCode: 'P030201',
            name: 'B.A. (Ed.) Business Education',
            degreeTitle: 'B.A. (Ed.)',
            programmeDescription: 'Vocational business studies, accounting pedagogy, and office information systems.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU207',
            programmeCode: 'P030202',
            name: 'B.A. (Ed.) Early Childhood Education',
            degreeTitle: 'B.A. (Ed.)',
            programmeDescription: 'Early childhood development, play-based learning heuristics, and child psychology.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU208',
            programmeCode: 'P030203',
            name: 'B.A. (Ed.) Primary Education',
            degreeTitle: 'B.A. (Ed.)',
            programmeDescription: 'Foundational primary education teaching methods, literacy, and numeracy instruction.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'EFO',
        name: 'Education Foundation',
        hodEmail: 'hod.efo@noun.edu.ng',
        programmes: [
          {
            id: 'EDU206',
            programmeCode: 'P030301',
            name: 'B.A. (Ed.) English',
            degreeTitle: 'B.A. (Ed.)',
            programmeDescription: 'English pedagogical methods, linguistics for educators, and literature teaching.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU215',
            programmeCode: 'P030302',
            name: 'B.Sc. (Ed.) Environmental Education',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Environmental literacy, sustainability pedagogy, and ecological education.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU301',
            programmeCode: 'P030303',
            name: 'PGD Education (PGDE)',
            degreeTitle: 'PGDE',
            programmeDescription: 'Professional teaching qualification for university graduates in education pedagogy.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'EDU401',
            programmeCode: 'P030304',
            name: 'M.Ed. Educational Administration and Planning',
            degreeTitle: 'M.Ed.',
            programmeDescription: 'Educational governance, policy analysis, resource allocation, and school management.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'EDU402',
            programmeCode: 'P030305',
            name: 'M.Ed. Guidance and Counselling',
            degreeTitle: 'M.Ed.',
            programmeDescription: 'Advanced counselling psychology, psychometrics, and student mental health support.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'EDU403',
            programmeCode: 'P030306',
            name: 'M.Ed. Educational Technology',
            degreeTitle: 'M.Ed.',
            programmeDescription: 'Instructional system development, multimedia production, and distance learning platforms.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'EDU601',
            programmeCode: 'P030307',
            name: 'Ph.D. Educational Administration and Planning',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into national educational planning and institutional leadership.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'EDU602',
            programmeCode: 'P030308',
            name: 'Ph.D. Guidance and Counselling',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral dissertation in psychotherapy models and school counseling frameworks.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'EDU603',
            programmeCode: 'P030309',
            name: 'Ph.D. Educational Foundations',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Philosophical, historical, and sociological foundations of modern education.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'HHK',
        name: 'Health and Human Kinetic Education',
        hodEmail: 'hod.hhk@noun.edu.ng',
        programmes: [
          {
            id: 'EDU209',
            programmeCode: 'P030401',
            name: 'B.Sc. (Ed.) Health Education',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'School health instruction, community health promotion, and epidemiology for teachers.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'EDU210',
            programmeCode: 'P030402',
            name: 'B.Sc. (Ed.) Human Kinetics',
            degreeTitle: 'B.Sc. (Ed.)',
            programmeDescription: 'Physical education pedagogy, sports biomechanics, exercise physiology, and athletics coaching.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'LIS',
        name: 'Library and Information Science',
        hodEmail: 'hod.lis@noun.edu.ng',
        programmes: [
          {
            id: 'EDU212',
            programmeCode: 'P030501',
            name: 'BLIS Library and Information Science',
            degreeTitle: 'BLIS',
            programmeDescription: 'Information retrieval systems, cataloguing, digital libraries, and archival management.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
    ],
  },

  // 4. Faculty of Health Sciences (7 Programmes)
  {
    id: 'hsc',
    facultyCode: 'F04',
    name: 'Faculty of Health Sciences',
    deanEmail: 'dean.health@noun.edu.ng',
    departments: [
      {
        id: 'EHS',
        name: 'Environmental Health Science',
        hodEmail: 'hod.ehs@noun.edu.ng',
        programmes: [
          {
            id: 'HSC201',
            programmeCode: 'P040101',
            name: 'B.Sc. Environmental Health',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Sanitation inspection, environmental toxicology, occupational safety, and pollution control.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'NSC',
        name: 'Nursing Science',
        hodEmail: 'hod.nsc@noun.edu.ng',
        programmes: [
          {
            id: 'HSC202',
            programmeCode: 'P040201',
            name: 'B.N.Sc. Nursing Science',
            degreeTitle: 'B.N.Sc.',
            programmeDescription: 'Clinical nursing care, therapeutics, maternal and child health, and community nursing.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'HSC205',
            programmeCode: 'P040202',
            name: 'PGD Nursing Science',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in clinical nursing leadership and specialized medical-surgical care.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
        ],
      },
      {
        id: 'PHE',
        name: 'Public Health',
        hodEmail: 'hod.phe@noun.edu.ng',
        programmes: [
          {
            id: 'HSC203',
            programmeCode: 'P040301',
            name: 'B.Sc. Public Health',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Community health assessment, epidemiology, disease prevention, and health policy.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'HSC401',
            programmeCode: 'P040302',
            name: 'PGD Public Health',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in field epidemiology, health program monitoring, and health education.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'HSC501',
            programmeCode: 'P040303',
            name: 'M.Sc. Public Health',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Master level specialization in global health systems, biostatistics, and epidemic response.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'HSC601',
            programmeCode: 'P040304',
            name: 'Ph.D. Public Health',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into population health metrics, health disparities, and healthcare interventions.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
    ],
  },

  // 5. Faculty of Law (3 Programmes)
  {
    id: 'law',
    facultyCode: 'F05',
    name: 'Faculty of Law',
    deanEmail: 'dean.law@noun.edu.ng',
    departments: [
      {
        id: 'LLW',
        name: 'Law',
        hodEmail: 'hod.law@noun.edu.ng',
        programmes: [
          {
            id: 'LAW301',
            programmeCode: 'P050101',
            name: 'LL.B. Bachelor of Laws',
            degreeTitle: 'LL.B.',
            programmeDescription: 'Constitutional law, contracts, criminal law, land law, torts, equity, commercial law, and jurisprudence.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'LAW401',
            programmeCode: 'P050102',
            name: 'LL.M. Master of Laws',
            degreeTitle: 'LL.M.',
            programmeDescription: 'Master of Laws in international trade, intellectual property, corporate governance, and comparative law.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'LAW601',
            programmeCode: 'P050103',
            name: 'Ph.D. in Law',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral legal research advancing statutory doctrine, human rights, and judicial administration.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
    ],
  },

  // 6. Faculty of Management Sciences (32 Programmes)
  {
    id: 'msc',
    facultyCode: 'F06',
    name: 'Faculty of Management Sciences',
    deanEmail: 'dean.mgmt@noun.edu.ng',
    departments: [
      {
        id: 'FST',
        name: 'Financial Studies',
        hodEmail: 'hod.fst@noun.edu.ng',
        programmes: [
          {
            id: 'MSC201',
            programmeCode: 'P060101',
            name: 'B.Sc. Accounting',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Financial reporting, auditing, taxation, cost accounting, and public sector accounting (IPSAS).',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC202',
            programmeCode: 'P060102',
            name: 'B.Sc. Banking and Finance',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Capital market dynamics, commercial banking operations, credit analysis, and corporate finance.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC314',
            programmeCode: 'P060103',
            name: 'PGD Accounting',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate bridge curriculum in forensic accounting, auditing standards, and financial management.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'MSC315',
            programmeCode: 'P060104',
            name: 'PGD Banking and Finance',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in banking regulations, financial institutions, and portfolio analysis.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'MSC417',
            programmeCode: 'P060105',
            name: 'M.Sc. Accounting',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Empirical research in corporate financial disclosure, audit quality, and international accounting.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC418',
            programmeCode: 'P060106',
            name: 'M.Sc. Banking and Finance',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced studies in financial risk management, monetary policy, and fintech structures.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC419',
            programmeCode: 'P060107',
            name: 'M.Sc. Financial Management',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Corporate restructuring, strategic investment evaluation, and international financial operations.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC604',
            programmeCode: 'P060108',
            name: 'Ph.D. Accounting',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral dissertation in behavioural accounting, audit independence, and governance metrics.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'MSC605',
            programmeCode: 'P060109',
            name: 'Ph.D. Banking and Finance',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral thesis in banking stability, systemic risk, and development financing.',
            level: ProgrammeLevel.DOCTORATE,
          },
          {
            id: 'MSC606',
            programmeCode: 'P060110',
            name: 'Ph.D. Financial Management',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into asset valuation models and capital allocation dynamics.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'BUS',
        name: 'Business Administration',
        hodEmail: 'hod.bus@noun.edu.ng',
        programmes: [
          {
            id: 'MSC203',
            programmeCode: 'P060201',
            name: 'B.Sc. Business Administration',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Organizational strategy, leadership dynamics, operations management, and international business.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC206',
            programmeCode: 'P060202',
            name: 'B.Sc. Marketing',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Consumer behaviour, digital brand strategy, sales engineering, and marketing communications.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC216',
            programmeCode: 'P060203',
            name: 'B.Sc. Supply Chain Management',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Procurement logistics, inventory optimization, distribution networks, and global supply chains.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC301',
            programmeCode: 'P060204',
            name: 'PGD Business Administration',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma providing core foundational business management competencies.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'MSC402',
            programmeCode: 'P060205',
            name: 'M.Sc. Business Administration',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Academic research in organizational agility, strategic alignment, and managerial economics.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC403',
            programmeCode: 'P060206',
            name: 'M.Sc. Marketing',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced marketing research, brand equity metrics, and customer relationship analytics.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC501',
            programmeCode: 'P060207',
            name: 'MBA Master of Business Administration',
            degreeTitle: 'MBA',
            programmeDescription: 'Executive professional degree in business leadership, enterprise strategy, and corporate governance.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC601',
            programmeCode: 'P060208',
            name: 'Ph.D. Business Administration',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into organizational theory, enterprise longevity, and strategic competitiveness.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'ENT',
        name: 'Entrepreneurship Studies',
        hodEmail: 'hod.ent@noun.edu.ng',
        programmes: [
          {
            id: 'MSC204',
            programmeCode: 'P060301',
            name: 'B.Sc. Entrepreneurship and Innovation',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Venture creation, business model generation, seed financing, and startup growth.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC209',
            programmeCode: 'P060302',
            name: 'B.Sc. Cooperative Management',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Cooperative economics, micro-credit associations, mutual enterprise governance, and rural cooperatives.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC302',
            programmeCode: 'P060303',
            name: 'PGD Entrepreneurship',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in SME management, innovation strategy, and business feasibility studies.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'MSC404',
            programmeCode: 'P060304',
            name: 'M.Sc. Entrepreneurship',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Scholarly research into entrepreneurial ecosystems, social ventures, and technology commercialization.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC503',
            programmeCode: 'P060305',
            name: 'M.Ent Master of Entrepreneurship',
            degreeTitle: 'M.Ent',
            programmeDescription: 'Professional master program for enterprise founders and venture managers.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC603',
            programmeCode: 'P060306',
            name: 'Ph.D. Entrepreneurship',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research examining entrepreneurial dynamics, policy frameworks, and innovation clusters.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'PAD',
        name: 'Public Administration',
        hodEmail: 'hod.pad@noun.edu.ng',
        programmes: [
          {
            id: 'MSC207',
            programmeCode: 'P060401',
            name: 'B.Sc. Public Administration',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Bureaucracy studies, public sector governance, administrative law, and civic service delivery.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'MSC303',
            programmeCode: 'P060402',
            name: 'PGD Public Administration',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in public administration and administrative ethics.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'MSC406',
            programmeCode: 'P060403',
            name: 'M.Sc. Public Administration',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Scholarly research in comparative administrative systems, policy evaluation, and civil service reforms.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC407',
            programmeCode: 'P060404',
            name: 'M.Sc. Local Government and Development Studies',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Decentralization policies, municipal finance, grassroot development, and local governance.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC502',
            programmeCode: 'P060405',
            name: 'MPA Master of Public Administration',
            degreeTitle: 'MPA',
            programmeDescription: 'Executive master degree for senior civil servants, public directors, and parastatal managers.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC602',
            programmeCode: 'P060406',
            name: 'Ph.D. Public Administration',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into public policy execution, institutional capacity, and anti-corruption frameworks.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'CPE',
        name: 'CEMBA/CEMPA Executive Programmes',
        hodEmail: 'hod.cpe@noun.edu.ng',
        programmes: [
          {
            id: 'MSC415',
            programmeCode: 'P060501',
            name: 'CEMBA Commonwealth Executive Master of Business Administration',
            degreeTitle: 'CEMBA',
            programmeDescription: 'Executive leadership, global corporate strategy, and operations across Commonwealth jurisdictions.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'MSC416',
            programmeCode: 'P060502',
            name: 'CEMPA Commonwealth Executive Master of Public Administration',
            degreeTitle: 'CEMPA',
            programmeDescription: 'Executive public administration, multilateral policy coordination, and public finance management.',
            level: ProgrammeLevel.MASTERS,
          },
        ],
      },
    ],
  },

  // 7. Faculty of Sciences (6 Programmes)
  {
    id: 'sci',
    facultyCode: 'F07',
    name: 'Faculty of Sciences',
    deanEmail: 'dean.sciences@noun.edu.ng',
    departments: [
      {
        id: 'BIO',
        name: 'Biology',
        hodEmail: 'hod.bio@noun.edu.ng',
        programmes: [
          {
            id: 'SCI201',
            programmeCode: 'P070101',
            name: 'B.Sc. Biology',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Ecology, cellular biology, genetics, morphology, developmental biology, and biotechnology.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'CHM',
        name: 'Chemistry',
        hodEmail: 'hod.chm@noun.edu.ng',
        programmes: [
          {
            id: 'SCI202',
            programmeCode: 'P070201',
            name: 'B.Sc. Chemistry',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Organic, inorganic, analytical, and physical chemistry, spectroscopy, and industrial chemistry.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'MTH',
        name: 'Mathematics',
        hodEmail: 'hod.mth@noun.edu.ng',
        programmes: [
          {
            id: 'SCI206',
            programmeCode: 'P070301',
            name: 'B.Sc. Mathematics',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Pure mathematics, real and complex analysis, linear algebra, topology, and differential equations.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SCI207',
            programmeCode: 'P070302',
            name: 'B.Sc. Mathematics and Computer Science',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Discrete mathematics, computational theory, numerical analysis, algorithms, and applied mathematics.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'PHY',
        name: 'Physics',
        hodEmail: 'hod.phy@noun.edu.ng',
        programmes: [
          {
            id: 'SCI208',
            programmeCode: 'P070401',
            name: 'B.Sc. Physics',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Classical mechanics, quantum physics, electromagnetism, optics, solid state physics, and electronics.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'ESC',
        name: 'Environmental Science',
        hodEmail: 'hod.esc@noun.edu.ng',
        programmes: [
          {
            id: 'SCI209',
            programmeCode: 'P070501',
            name: 'B.Sc. Environmental Science and Resource Management',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Ecosystem management, environmental impact assessment, geomorphology, and natural resource conservation.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
    ],
  },

  // 8. Faculty of Social Sciences (28 Programmes)
  {
    id: 'ssc',
    facultyCode: 'F08',
    name: 'Faculty of Social Sciences',
    deanEmail: 'dean.socsci@noun.edu.ng',
    departments: [
      {
        id: 'MAC',
        name: 'Mass Communication',
        hodEmail: 'hod.mac@noun.edu.ng',
        programmes: [
          {
            id: 'SSC201',
            programmeCode: 'P080101',
            name: 'B.Sc. Mass Communication',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Print journalism, broadcasting, media ethics, public relations, and communications theory.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC205',
            programmeCode: 'P080102',
            name: 'B.Sc. Broadcast Journalism',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Television production, radio documentary, broadcast news editing, and multimedia broadcasting.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC207',
            programmeCode: 'P080103',
            name: 'B.Sc. Film and Multimedia Studies',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Cinematography, digital video editing, screenwriting, and animation production.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC303',
            programmeCode: 'P080104',
            name: 'PGD Mass Communication',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate bridge curriculum in mass communication theory, media law, and journalistic writing.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'SSC402',
            programmeCode: 'P080105',
            name: 'M.Sc. Mass Communication',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced research in media sociology, development communication, and digital culture.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC602',
            programmeCode: 'P080106',
            name: 'Ph.D. Mass Communication',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into media policy, digital journalism trends, and audience reception theories.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'CSS',
        name: 'Criminology and Security Studies',
        hodEmail: 'hod.css@noun.edu.ng',
        programmes: [
          {
            id: 'SSC202',
            programmeCode: 'P080201',
            name: 'B.Sc. Criminology and Security Studies',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Criminal justice administration, penology, crime prevention, policing, and intelligence gathering.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC301',
            programmeCode: 'P080202',
            name: 'PGD Criminology and Security Studies',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in intelligence operations, criminal profiling, and private security management.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'SSC401',
            programmeCode: 'P080203',
            name: 'M.Sc. Criminology and Security Studies',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced studies in transnational organized crime, cybersecurity threats, and correctional reforms.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC501',
            programmeCode: 'P080204',
            name: 'Master of International Relations and Diplomacy',
            degreeTitle: 'MIRD',
            programmeDescription: 'Foreign policy analysis, diplomatic protocol, international treaties, and multilateral negotiation.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC601',
            programmeCode: 'P080205',
            name: 'Ph.D. Criminology and Security Studies',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research in national security strategy, victimology, and counter-insurgency policies.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'DES',
        name: 'Development Studies',
        hodEmail: 'hod.des@noun.edu.ng',
        programmes: [
          {
            id: 'SSC203',
            programmeCode: 'P080301',
            name: 'B.Sc. Development Studies',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Socio-economic development paradigms, poverty alleviation, project monitoring, and sustainable development.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'ECO',
        name: 'Economics',
        hodEmail: 'hod.eco@noun.edu.ng',
        programmes: [
          {
            id: 'SSC204',
            programmeCode: 'P080401',
            name: 'B.Sc. Economics',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Microeconomics, macroeconomics, econometrics, public finance, monetary economics, and international trade.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC302',
            programmeCode: 'P080402',
            name: 'PGD Economics',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in quantitative economic methods and macroeconomic policy analysis.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'SSC412',
            programmeCode: 'P080403',
            name: 'M.Sc. Economics',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced econometric modeling, development economics, applied microeconomics, and fiscal policy.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC503',
            programmeCode: 'P080404',
            name: 'Master of Financial Economics',
            degreeTitle: 'MFE',
            programmeDescription: 'Professional financial economics, asset pricing, banking economics, and derivative markets.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC604',
            programmeCode: 'P080405',
            name: 'Ph.D. Economics',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into monetary transmission mechanisms, growth analytics, and trade policy.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'POL',
        name: 'Political Science',
        hodEmail: 'hod.pol@noun.edu.ng',
        programmes: [
          {
            id: 'SSC206',
            programmeCode: 'P080501',
            name: 'B.Sc. Political Science',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Political theory, comparative politics, political economy, public policy, and constitutional development.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC209',
            programmeCode: 'P080502',
            name: 'B.Sc. International Relations',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Global geopolitics, international organizations, diplomacy, and foreign policy decision-making.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC405',
            programmeCode: 'P080503',
            name: 'M.Sc. Political Science',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Scholarly research into democratic governance, electoral systems, and African political dynamics.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC605',
            programmeCode: 'P080504',
            name: 'Ph.D. Political Science',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research in statehood, political institutions, and international political economy.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'PCR',
        name: 'Peace Studies and Conflict Resolution',
        hodEmail: 'hod.pcr@noun.edu.ng',
        programmes: [
          {
            id: 'SSC208',
            programmeCode: 'P080601',
            name: 'B.Sc. Peace Studies and Conflict Resolution',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Mediation techniques, conflict analysis, peacebuilding, disarmament, and humanitarian law.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'SSC304',
            programmeCode: 'P080602',
            name: 'PGD Peace Studies and Conflict Resolution',
            degreeTitle: 'PGD',
            programmeDescription: 'Postgraduate diploma in dispute settlement, negotiation tactics, and restorative justice.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'SSC403',
            programmeCode: 'P080603',
            name: 'M.Sc. Peace Studies and Conflict Resolution',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced conflict transformation, peacekeeping operations, and post-conflict reconstruction.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC502',
            programmeCode: 'P080604',
            name: 'Master of Peace and Security Studies',
            degreeTitle: 'MPSS',
            programmeDescription: 'Strategic security studies, early warning systems, counter-terrorism, and regional peace architectures.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC504',
            programmeCode: 'P080605',
            name: 'Master of Conflict Resolution and Governance',
            degreeTitle: 'MCRG',
            programmeDescription: 'Institutional dispute management, electoral conflict mitigation, and community mediation.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'SSC603',
            programmeCode: 'P080606',
            name: 'Ph.D. Peace Studies and Conflict Resolution',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into structural violence, peace accords, and transitional justice systems.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'TSM',
        name: 'Tourism Studies',
        hodEmail: 'hod.tsm@noun.edu.ng',
        programmes: [
          {
            id: 'SSC210',
            programmeCode: 'P080701',
            name: 'B.Sc. Tourism Studies',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Hospitality management, destination planning, cultural heritage tourism, and ecotourism.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
    ],
  },

  // 9. Faculty of Computing (7 Programmes)
  {
    id: 'cmp',
    facultyCode: 'F13',
    name: 'Faculty of Computing',
    deanEmail: 'dean.computing@noun.edu.ng',
    departments: [
      {
        id: 'CIT',
        name: 'Computer Science',
        hodEmail: 'hod.cit@noun.edu.ng',
        programmes: [
          {
            id: 'CMP203',
            programmeCode: 'P130101',
            name: 'B.Sc. Computer Science',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Algorithms, data structures, compiler design, software engineering, artificial intelligence, and operating systems.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
      {
        id: 'IFT',
        name: 'Information Systems and Technology',
        hodEmail: 'hod.ift@noun.edu.ng',
        programmes: [
          {
            id: 'CMP205',
            programmeCode: 'P130201',
            name: 'B.Sc. Information Technology',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Enterprise IT infrastructure, web engineering, cloud computing, database administration, and IT service management.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
          {
            id: 'CMP301',
            programmeCode: 'P130202',
            name: 'PGD Information Technology',
            degreeTitle: 'PGD',
            programmeDescription: 'Conversion postgraduate diploma for technical graduates moving into enterprise IT and software systems.',
            level: ProgrammeLevel.POSTGRADUATE_DIPLOMA,
          },
          {
            id: 'CMP401',
            programmeCode: 'P130203',
            name: 'M.Sc. Information Technology',
            degreeTitle: 'M.Sc.',
            programmeDescription: 'Advanced distributed systems, data engineering, cloud architectures, and IT governance.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'CMP501',
            programmeCode: 'P130204',
            name: 'Master of Cyber Security and Forensics',
            degreeTitle: 'MCSF',
            programmeDescription: 'Digital forensics, incident response, network penetration testing, and defensive cyber architecture.',
            level: ProgrammeLevel.MASTERS,
          },
          {
            id: 'CMP601',
            programmeCode: 'P130205',
            name: 'Ph.D. Information Technology',
            degreeTitle: 'Ph.D.',
            programmeDescription: 'Doctoral research into intelligent systems, distributed architectures, and big data engineering.',
            level: ProgrammeLevel.DOCTORATE,
          },
        ],
      },
      {
        id: 'CYB',
        name: 'Cyber Security',
        hodEmail: 'hod.cyb@noun.edu.ng',
        programmes: [
          {
            id: 'CMP206',
            programmeCode: 'P130301',
            name: 'B.Sc. Cyber Security',
            degreeTitle: 'B.Sc.',
            programmeDescription: 'Network defense, ethical hacking, cryptography, security operations center (SOC) analytics, and malware reverse engineering.',
            level: ProgrammeLevel.UNDERGRADUATE,
          },
        ],
      },
    ],
  },
];

export const SAMPLE_COURSES = [
  // Computer Science (CIT)
  { courseCode: 'CIT 211', courseTitle: 'Introduction to Operating Systems', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'CMP203', departmentId: 'CIT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 200 },
  { courseCode: 'CIT 215', courseTitle: 'Introduction to Programming (C++)', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 1, programmeId: 'CMP203', departmentId: 'CIT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 200 },
  { courseCode: 'CIT 304', courseTitle: 'Data Structures and Algorithms', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'CMP203', departmentId: 'CIT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },
  { courseCode: 'CIT 311', courseTitle: 'Computer Networks and Data Communications', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'CMP203', departmentId: 'CIT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },
  { courseCode: 'CIT 401', courseTitle: 'Software Engineering Principles', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'CMP203', departmentId: 'CIT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 400 },
  { courseCode: 'CIT 415', courseTitle: 'Artificial Intelligence and Neural Networks', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'CMP203', departmentId: 'CIT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 400 },
  { courseCode: 'CIT 811', courseTitle: 'Advanced Distributed Database Engineering', creditUnits: 3, lectureHours: 3, tutorialHours: 0, practicalHours: 0, programmeId: 'CMP401', departmentId: 'IFT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 800 },
  { courseCode: 'CIT 815', courseTitle: 'Cloud Architecture & Enterprise Computing', creditUnits: 3, lectureHours: 3, tutorialHours: 0, practicalHours: 0, programmeId: 'CMP401', departmentId: 'IFT', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 800 },

  // Cyber Security (CYB)
  { courseCode: 'CYB 201', courseTitle: 'Fundamentals of Cyber Security', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'CMP206', departmentId: 'CYB', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 200 },
  { courseCode: 'CYB 301', courseTitle: 'Cryptographic Protocols & Network Defense', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 1, programmeId: 'CMP206', departmentId: 'CYB', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },

  // Agricultural Economics (AEE)
  { courseCode: 'AGR 201', courseTitle: 'General Agriculture and Agribusiness', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'AGR201', departmentId: 'AEE', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 200 },
  { courseCode: 'AEE 301', courseTitle: 'Agricultural Marketing and Cooperatives', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'AGR201', departmentId: 'AEE', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },

  // Law (LLW)
  { courseCode: 'LAW 311', courseTitle: 'Constitutional and Administrative Law I', creditUnits: 4, lectureHours: 3, tutorialHours: 1, practicalHours: 0, programmeId: 'LAW301', departmentId: 'LLW', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },
  { courseCode: 'LAW 411', courseTitle: 'Oil and Gas Law & Environmental Jurisprudence', creditUnits: 4, lectureHours: 3, tutorialHours: 1, practicalHours: 0, programmeId: 'LAW301', departmentId: 'LLW', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 400 },

  // Financial Studies (FST)
  { courseCode: 'ACC 201', courseTitle: 'Financial Accounting I', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'MSC201', departmentId: 'FST', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 200 },
  { courseCode: 'ACC 301', courseTitle: 'Cost and Management Accounting', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'MSC201', departmentId: 'FST', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },

  // Economics (ECO)
  { courseCode: 'ECO 201', courseTitle: 'Principles of Microeconomics I', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'SSC204', departmentId: 'ECO', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 200 },
  { courseCode: 'ECO 301', courseTitle: 'Advanced Macroeconomics and Policy', creditUnits: 3, lectureHours: 2, tutorialHours: 1, practicalHours: 0, programmeId: 'SSC204', departmentId: 'ECO', semester: AcademicSemester.FIRST_SEMESTER, session: '2026/2027', level: 300 },
];
