name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm run install:all

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./server

      - name: Build Frontend Client (Next.js)
        run: npm run build --workspace=client
        env:
          NEXT_PUBLIC_API_URL: "https://noun-hrms.onrender.com"

      - name: Deploy Frontend to Firebase Hosting
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOUNHRMS }}
          channelId: live
          projectId: nounhrms
